application: tangblack
version: 1
runtime: python
api_version: 1

handlers:
- url: /template/.*
  static_dir: /template
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /.*
  script: main.py
